### ISSUE TITLE
updateFunctionCode is not a function

### ISSUE THREAD

**Issue by sharok** [ThoughtWorksStudios/node-aws-lambda#16]
Hi. I have the following error on deploying:
>TypeError: lambda.updateFunctionCode is not a function
    at C:\Projects\test-project\node_modules\node-aws-lambda\index.js:108:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:405:3)

Where is a problem?
@wpc

**Comment by sharok** [comment]
I used old aws-sdk. After update all works fine.
